### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by kamataryo**
Keep consistency about trailing whitespace triming.
This may be helpful for the case of  https://github.com/timwaters/mapwarper/pull/120#issuecomment-296447875 and save communication costs.

How about this?

### CODE REVIEW

**Comment by timwaters** [comment]
Was the extra whitespace was being added by your editor, rather than it being removed?

**Comment by kamataryo** [comment]
No, my text editor was trying to remove extra whitespaces.
the `.editorconfig` is a configuration file for [EditorConfig](http://editorconfig.org/). It defines and maintains consistent coding styles between different editors and IDEs. In this case, I add a configuration not to trim extra trailing whitespace. It prevents unnecessary whitspace trimming contamination.
We don’t care about tiny whitespace remaining problem, so that It's better for EditorConfig to decide where to put whitespace, for consistency and time saving.

**Comment by timwaters** [comment]
Ahh yes! I see. Many thanks. I was looking at the revert commit, rather than the initial one, sorry!

**Comment by kamataryo** [comment]
This makes easier to make commit , Thanks a lot!

**Pull request merged**
