### PR TITLE
Add locale switcher

### PR DESCRIPTION
**Pull request by kamataryo**
Hi Tim,

We talked about locale switcher at #122.
This PR adds query parameter locale routing and a switcher in the header. I hope this would be our help!
locale-switcher

### CODE REVIEW

**Comment by kamataryo** [comment]
issued at #123

**Comment by timwaters** [comment]
Looking good, will have to review this myself when I get the chance :+1:

**Comment by timwaters** [comment]
The NL translations also need checking I think, as there may be instance specific strings, and possibly missing ones from master.

**Comment by timwaters** [comment]
many thanks! I've reviewed this and merged it in. I'll add in a check to rescue I18n::InvalidLocale in case the system has just one locale enabled, and the user asks for another, and Ill add in I18n.config.enforce_available_locales to true as thats changed in rails.

**Comment by timwaters** [comment]
now live. Many thanks @kamataryo :+1:

**Comment by timwaters** [comment]
mapwarper_locale

**Pull request merged**
