### PR TITLE
Fix duplicated spacing typo in mailer template.

### PR DESCRIPTION
**Pull request by KamataRyo**
in `app/views/devise/mailer/confirmation_instructions.html.erb`.
My text editor also fixed some consistency, such as trailing spaces ;)

### CODE REVIEW

**Comment by timwaters** [comment]
hi the mailer template text was changed recently perhaps after you made your change - could you add these back?

**Comment by KamataRyo** [comment]
Sorry about the miss merging of mailer texts. I fixed it back.

I noticed that this PR contains a mention about bundler at `README.md`. Global vs local depends on the projects strategy, so this should be removed it if not appropriate. How do you think about it?
https://github.com/KamataRyo/mapwarper/blame/master/README.md#L76

**Comment by timwaters** [comment]
Many thanks!

Yeah, I guess it could be removed... the readme is meant for easy development and not really for production / staging deployment etc.  For example, I mainly use RVM for handling gemsets etc, and I could add that in the readme too. I suppose it's a strategy

**Comment by KamataRyo** [comment]
I agree that it was too definitive for the readme and I pushed revertive commit.
Thanks for advices!

**Comment by KamataRyo** [comment]
By the way, I saw the new time slider when I refreshed my local instance.
It's great feature and quite helpful for spatial and temporal collaboration for geological information!

**Comment by timwaters** [comment]
cheers!

Also - Many thanks for the pull request, I really appreciate your work :-)

**Pull request merged**
